# Generated by Django 5.0.14 on 2026-03-16 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentWebhookEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("gateway", models.CharField(default="stripe", max_length=20)),
                ("event_id", models.CharField(max_length=255, unique=True)),
                ("event_type", models.CharField(max_length=255)),
                ("payload", models.JSONField(default=dict)),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="payments.payment"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentIdempotency",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(choices=[("create", "Create"), ("verify", "Verify")], max_length=20)),
                ("key", models.CharField(max_length=255)),
                ("response_data", models.JSONField(default=dict)),
                ("status_code", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_idempotency",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "action", "key")},
            },
        ),
        migrations.AddIndex(
            model_name="paymentwebhookevent",
            index=models.Index(fields=["gateway", "event_id"], name="payments_pa_gateway_1efd92_idx"),
        ),
        migrations.AddIndex(
            model_name="paymentidempotency",
            index=models.Index(fields=["user", "action", "key"], name="payments_pa_user_id_92c48d_idx"),
        ),
    ]
