# Generated by Django 5.0.14 on 2026-02-06 10:32

import django.db.models.deletion
import hashid_field.field
from django.conf import settings
from django.db import migrations, models

import common.storages


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    hashid_field.field.HashidAutoField(
                        alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
                        min_length=7,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("business_name", models.CharField(max_length=255)),
                ("display_name", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=common.storages.PublicS3Boto3StorageWithCDN,
                        upload_to=common.storages.UniqueFilePathGenerator("vendors/logos"),
                    ),
                ),
                (
                    "banner",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=common.storages.PublicS3Boto3StorageWithCDN,
                        upload_to=common.storages.UniqueFilePathGenerator("vendors/banners"),
                    ),
                ),
                ("gstin", models.CharField(blank=True, max_length=50)),
                ("pan", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("suspended", "Suspended"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("rating", models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ("rating_count", models.PositiveIntegerField(default=0)),
                ("product_count", models.PositiveIntegerField(default=0)),
                (
                    "commission_tier",
                    models.CharField(
                        choices=[("standard", "Standard"), ("gold", "Gold"), ("platinum", "Platinum")],
                        default="standard",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    hashid_field.field.HashidAutoField(
                        alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
                        min_length=7,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("account_name", models.CharField(max_length=255)),
                ("account_number", models.CharField(max_length=50)),
                ("ifsc_code", models.CharField(max_length=20)),
                ("bank_name", models.CharField(max_length=100)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("verified", "Verified"), ("failed", "Failed")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="bank_accounts", to="vendors.vendor"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VendorDocument",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    hashid_field.field.HashidAutoField(
                        alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
                        min_length=7,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("gst", "GST Certificate"),
                            ("pan", "PAN Card"),
                            ("cancel_cheque", "Cancelled Cheque"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("doc_number", models.CharField(blank=True, max_length=100)),
                (
                    "file",
                    models.FileField(
                        storage=common.storages.PublicS3Boto3StorageWithCDN,
                        upload_to=common.storages.UniqueFilePathGenerator("vendors/documents"),
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("verified", "Verified"), ("rejected", "Rejected")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="documents", to="vendors.vendor"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
