"""bootstrap_marketplace_schema

Revision ID: 7f3c17e67b4a
Revises: b7c1d2e3f4a5
Create Date: 2026-03-18 09:14:31.628880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7f3c17e67b4a'
down_revision: Union[str, Sequence[str], None] = 'b7c1d2e3f4a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('slug', sqlmodel.AutoString(length=150), nullable=False),
    sa.Column('logo_url', sqlmodel.AutoString(length=500), nullable=False),
    sa.Column('description', sqlmodel.AutoString(length=1000), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brands_slug'), ['slug'], unique=True)

    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('slug', sqlmodel.AutoString(length=150), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.AutoString(length=1000), nullable=False),
    sa.Column('icon_url', sqlmodel.AutoString(length=500), nullable=False),
    sa.Column('image_url', sqlmodel.AutoString(length=500), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('attributes_json', sqlmodel.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_slug'), ['slug'], unique=True)

    op.create_table('coupons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.AutoString(length=80), nullable=False),
    sa.Column('description', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('type', sa.Enum('PERCENTAGE', 'FIXED', name='coupontype'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('min_order_value', sa.Float(), nullable=False),
    sa.Column('max_discount', sa.Float(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.Column('usage_limit', sa.Integer(), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coupons_code'), ['code'], unique=True)

    op.create_table('delivery_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.AutoString(length=120), nullable=False),
    sa.Column('code', sqlmodel.AutoString(length=50), nullable=False),
    sa.Column('state', sqlmodel.AutoString(length=120), nullable=False),
    sa.Column('city', sqlmodel.AutoString(length=120), nullable=False),
    sa.Column('pincodes_json', sqlmodel.AutoString(), nullable=False),
    sa.Column('cod_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('shipping_rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delivery_zones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delivery_zones_code'), ['code'], unique=True)

    op.create_table('logistics_hubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.AutoString(length=120), nullable=False),
    sa.Column('code', sqlmodel.AutoString(length=50), nullable=False),
    sa.Column('address', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('city', sqlmodel.AutoString(length=120), nullable=False),
    sa.Column('state', sqlmodel.AutoString(length=120), nullable=False),
    sa.Column('hub_type', sa.Enum('NATIONAL', 'REGIONAL', 'LOCAL', name='hubtype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('logistics_hubs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_logistics_hubs_code'), ['code'], unique=True)

    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('phone', sqlmodel.AutoString(length=20), nullable=False),
    sa.Column('line1', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('line2', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('city', sqlmodel.AutoString(length=120), nullable=False),
    sa.Column('state', sqlmodel.AutoString(length=120), nullable=False),
    sa.Column('pincode', sqlmodel.AutoString(length=20), nullable=False),
    sa.Column('country', sqlmodel.AutoString(length=120), nullable=False),
    sa.Column('landmark', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('type', sqlmodel.AutoString(length=20), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_addresses_user_id'), ['user_id'], unique=False)

    op.create_table('carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('coupon_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_carts_user_id'), ['user_id'], unique=True)

    op.create_table('chat_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sqlmodel.AutoString(length=120), nullable=False),
    sa.Column('device_label', sqlmodel.AutoString(length=120), nullable=False),
    sa.Column('identity_key_public', sqlmodel.AutoString(length=4096), nullable=False),
    sa.Column('signed_prekey_public', sqlmodel.AutoString(length=4096), nullable=False),
    sa.Column('signed_prekey_signature', sqlmodel.AutoString(length=4096), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_devices_device_id'), ['device_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_chat_devices_user_id'), ['user_id'], unique=False)

    op.create_table('chat_key_backups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('backup_blob', sqlmodel.AutoString(length=32768), nullable=False),
    sa.Column('backup_version', sqlmodel.AutoString(length=20), nullable=False),
    sa.Column('salt', sqlmodel.AutoString(length=1024), nullable=False),
    sa.Column('metadata_json', sqlmodel.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_key_backups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_key_backups_user_id'), ['user_id'], unique=False)

    op.create_table('gift_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.AutoString(length=80), nullable=False),
    sa.Column('initial_amount', sa.Integer(), nullable=False),
    sa.Column('remaining_amount', sa.Integer(), nullable=False),
    sa.Column('currency', sqlmodel.AutoString(length=3), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'REDEEMED', 'EXPIRED', 'DISABLED', name='giftcardstatus'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('redeemed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('redeemed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['redeemed_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gift_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gift_cards_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_gift_cards_redeemed_by_user_id'), ['redeemed_by_user_id'], unique=False)

    op.create_table('logistics_branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hub_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.AutoString(length=120), nullable=False),
    sa.Column('code', sqlmodel.AutoString(length=50), nullable=False),
    sa.Column('address', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('city', sqlmodel.AutoString(length=120), nullable=False),
    sa.Column('state', sqlmodel.AutoString(length=120), nullable=False),
    sa.Column('contact_phone', sqlmodel.AutoString(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hub_id'], ['logistics_hubs.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['delivery_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('logistics_branches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_logistics_branches_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_logistics_branches_hub_id'), ['hub_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_logistics_branches_zone_id'), ['zone_id'], unique=False)

    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('body', sqlmodel.AutoString(length=2000), nullable=False),
    sa.Column('type', sa.Enum('INFO', 'SUCCESS', 'WARNING', 'ERROR', 'PAYMENT', 'AUTH', 'SYSTEM', name='notificationtype'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_user_id'), ['user_id'], unique=False)

    op.create_table('notificationpreference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('websocket_enabled', sa.Boolean(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('push_enabled', sa.Boolean(), nullable=False),
    sa.Column('sms_enabled', sa.Boolean(), nullable=False),
    sa.Column('push_endpoint', sqlmodel.AutoString(length=2048), nullable=True),
    sa.Column('push_p256dh', sqlmodel.AutoString(length=512), nullable=True),
    sa.Column('push_auth', sqlmodel.AutoString(length=256), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notificationpreference', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notificationpreference_user_id'), ['user_id'], unique=True)

    op.create_table('payment_transactions',
    sa.Column('provider', sa.Enum('KHALTI', 'ESEWA', 'STRIPE', 'PAYPAL', 'WALLET', 'COD', name='paymentprovider'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sqlmodel.AutoString(length=3), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'INITIATED', 'COMPLETED', 'FAILED', 'REFUNDED', 'CANCELLED', name='paymentstatus'), nullable=False),
    sa.Column('purchase_order_id', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('purchase_order_name', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('provider_transaction_id', sqlmodel.AutoString(length=255), nullable=True),
    sa.Column('provider_pidx', sqlmodel.AutoString(length=255), nullable=True),
    sa.Column('return_url', sqlmodel.AutoString(length=500), nullable=False),
    sa.Column('website_url', sqlmodel.AutoString(length=500), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('extra_data', sqlmodel.AutoString(), nullable=True),
    sa.Column('failure_reason', sqlmodel.AutoString(length=500), nullable=True),
    sa.Column('captured_amount', sa.Integer(), nullable=False),
    sa.Column('refunded_amount', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sqlmodel.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_transactions_idempotency_key'), ['idempotency_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transactions_provider_pidx'), ['provider_pidx'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transactions_provider_transaction_id'), ['provider_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transactions_purchase_order_id'), ['purchase_order_id'], unique=False)

    op.create_table('shipping_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.AutoString(length=120), nullable=False),
    sa.Column('code', sqlmodel.AutoString(length=50), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('cod_enabled', sa.Boolean(), nullable=False),
    sa.Column('estimated_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['delivery_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shipping_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipping_options_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_shipping_options_zone_id'), ['zone_id'], unique=False)

    op.create_table('user_affinity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_affinity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_affinity_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_affinity_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_affinity_user_id'), ['user_id'], unique=False)

    op.create_table('wallet_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entry_type', sa.Enum('CREDIT', 'DEBIT', 'GIFT_CARD', 'REFUND', 'ADJUSTMENT', name='walletledgertype'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('reference_type', sqlmodel.AutoString(length=50), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('notes', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wallet_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wallet_ledger_reference_id'), ['reference_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallet_ledger_user_id'), ['user_id'], unique=False)

    op.create_table('chat_one_time_prekeys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('key_id', sa.Integer(), nullable=False),
    sa.Column('public_key', sqlmodel.AutoString(length=4096), nullable=False),
    sa.Column('is_consumed', sa.Boolean(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['chat_devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_one_time_prekeys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_one_time_prekeys_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_one_time_prekeys_key_id'), ['key_id'], unique=False)

    op.create_table('chat_signed_prekeys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('key_id', sa.Integer(), nullable=False),
    sa.Column('public_key', sqlmodel.AutoString(length=4096), nullable=False),
    sa.Column('signature', sqlmodel.AutoString(length=4096), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['chat_devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_signed_prekeys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_signed_prekeys_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_signed_prekeys_key_id'), ['key_id'], unique=False)

    op.create_table('delivery_agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.AutoString(length=120), nullable=False),
    sa.Column('phone', sqlmodel.AutoString(length=20), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'ASSIGNED', 'OFFLINE', 'ON_LEAVE', name='deliveryagentstatus'), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('current_load', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['logistics_branches.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delivery_agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delivery_agents_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_agents_user_id'), ['user_id'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sqlmodel.AutoString(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('coupon_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING_PAYMENT', 'CONFIRMED', 'PROCESSING', 'PACKED', 'SHIPPED', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED', 'RETURNED', name='orderstatus'), nullable=False),
    sa.Column('payment_method', sa.Enum('COD', 'KHALTI', 'ESEWA', 'STRIPE', 'PAYPAL', 'WALLET', name='paymentmethod'), nullable=False),
    sa.Column('payment_status', sa.Enum('PENDING', 'PAID', 'FAILED', 'REFUNDED', name='orderpaymentstatus'), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('discount', sa.Float(), nullable=False),
    sa.Column('shipping_charge', sa.Float(), nullable=False),
    sa.Column('tax', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('coupon_code', sqlmodel.AutoString(length=80), nullable=False),
    sa.Column('coupon_discount', sa.Float(), nullable=False),
    sa.Column('notes', sqlmodel.AutoString(length=1000), nullable=False),
    sa.Column('pricing_snapshot_json', sqlmodel.AutoString(), nullable=False),
    sa.Column('payment_transaction_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('shipped_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ),
    sa.ForeignKeyConstraint(['payment_transaction_id'], ['payment_transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_address_id'), ['address_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_order_number'), ['order_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_orders_payment_transaction_id'), ['payment_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_user_id'), ['user_id'], unique=False)

    op.create_table('payment_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sqlmodel.AutoString(length=100), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('payload_json', sqlmodel.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['payment_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_audit_logs_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_audit_logs_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_audit_logs_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('payment_refunds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='paymentrefundstatus'), nullable=False),
    sa.Column('destination', sqlmodel.AutoString(length=50), nullable=False),
    sa.Column('reason', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('provider_refund_id', sqlmodel.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['payment_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_refunds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_refunds_transaction_id'), ['transaction_id'], unique=False)

    op.create_table('payment_webhooks',
    sa.Column('provider', sa.Enum('KHALTI', 'ESEWA', 'STRIPE', 'PAYPAL', 'WALLET', 'COD', name='paymentprovider'), nullable=False),
    sa.Column('event_type', sqlmodel.AutoString(length=100), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('raw_payload', sqlmodel.AutoString(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sqlmodel.AutoString(length=45), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['payment_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipment_manifests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.AutoString(length=64), nullable=False),
    sa.Column('origin_hub_id', sa.Integer(), nullable=True),
    sa.Column('destination_hub_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('shipment_ids_json', sqlmodel.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'DISPATCHED', 'RECEIVED', 'RECONCILED', name='shipmentmanifeststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['logistics_branches.id'], ),
    sa.ForeignKeyConstraint(['destination_hub_id'], ['logistics_hubs.id'], ),
    sa.ForeignKeyConstraint(['origin_hub_id'], ['logistics_hubs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shipment_manifests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipment_manifests_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipment_manifests_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_shipment_manifests_destination_hub_id'), ['destination_hub_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipment_manifests_origin_hub_id'), ['origin_hub_id'], unique=False)

    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('business_name', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('display_name', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('slug', sqlmodel.AutoString(length=120), nullable=False),
    sa.Column('description', sqlmodel.AutoString(length=2000), nullable=False),
    sa.Column('logo_url', sqlmodel.AutoString(length=500), nullable=False),
    sa.Column('banner_url', sqlmodel.AutoString(length=500), nullable=False),
    sa.Column('gstin', sqlmodel.AutoString(length=80), nullable=False),
    sa.Column('pan', sqlmodel.AutoString(length=80), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'SUSPENDED', name='vendorstatus'), nullable=False),
    sa.Column('commission_tier', sa.Enum('STANDARD', 'PREMIUM', 'ENTERPRISE', name='commissiontier'), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('product_count', sa.Integer(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_reason', sqlmodel.AutoString(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendors_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendors_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_vendors_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('checkout_idempotency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checkout_idempotency', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checkout_idempotency_idempotency_key'), ['idempotency_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_checkout_idempotency_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_checkout_idempotency_user_id'), ['user_id'], unique=False)

    op.create_table('line_haul_trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manifest_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_number', sqlmodel.AutoString(length=50), nullable=False),
    sa.Column('driver_name', sqlmodel.AutoString(length=120), nullable=False),
    sa.Column('driver_phone', sqlmodel.AutoString(length=20), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'LOADED', 'IN_TRANSIT', 'ARRIVED', 'CANCELLED', name='linehaultripstatus'), nullable=False),
    sa.Column('departed_at', sa.DateTime(), nullable=True),
    sa.Column('arrived_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['manifest_id'], ['shipment_manifests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('line_haul_trips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_line_haul_trips_manifest_id'), ['manifest_id'], unique=False)

    op.create_table('order_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_PAYMENT', 'CONFIRMED', 'PROCESSING', 'PACKED', 'SHIPPED', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED', 'RETURNED', name='orderstatus'), nullable=False),
    sa.Column('note', sqlmodel.AutoString(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_status_history_order_id'), ['order_id'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('slug', sqlmodel.AutoString(length=180), nullable=False),
    sa.Column('short_description', sqlmodel.AutoString(length=500), nullable=False),
    sa.Column('description', sqlmodel.AutoString(length=3000), nullable=False),
    sa.Column('specifications_json', sqlmodel.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'ACTIVE', 'REJECTED', 'ARCHIVED', name='productstatus'), nullable=False),
    sa.Column('avg_rating', sa.Float(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_products_vendor_id'), ['vendor_id'], unique=False)

    op.create_table('vendor_bank_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('account_name', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('account_number', sqlmodel.AutoString(length=80), nullable=False),
    sa.Column('ifsc_code', sqlmodel.AutoString(length=50), nullable=False),
    sa.Column('bank_name', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'FAILED', name='bankaccountverificationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vendor_bank_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_bank_accounts_vendor_id'), ['vendor_id'], unique=False)

    op.create_table('vendor_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sqlmodel.AutoString(length=50), nullable=False),
    sa.Column('doc_number', sqlmodel.AutoString(length=120), nullable=False),
    sa.Column('file_url', sqlmodel.AutoString(length=500), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='vendordocumentstatus'), nullable=False),
    sa.Column('remarks', sqlmodel.AutoString(length=500), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vendor_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_documents_vendor_id'), ['vendor_id'], unique=False)

    op.create_table('vendor_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('vendor_order_number', sqlmodel.AutoString(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'PACKED', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'RETURNED', name='vendororderstatus'), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('commission', sa.Float(), nullable=False),
    sa.Column('vendor_amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vendor_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_orders_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_orders_vendor_id'), ['vendor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_orders_vendor_order_number'), ['vendor_order_number'], unique=True)

    op.create_table('vendor_payouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('commission_amount', sa.Float(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'PAID', 'FAILED', name='vendorpayoutstatus'), nullable=False),
    sa.Column('reference', sqlmodel.AutoString(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vendor_payouts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_payouts_vendor_id'), ['vendor_id'], unique=False)

    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('address', sqlmodel.AutoString(length=500), nullable=False),
    sa.Column('city', sqlmodel.AutoString(length=120), nullable=False),
    sa.Column('state', sqlmodel.AutoString(length=120), nullable=False),
    sa.Column('pincode', sqlmodel.AutoString(length=20), nullable=False),
    sa.Column('contact_phone', sqlmodel.AutoString(length=20), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_warehouses_vendor_id'), ['vendor_id'], unique=False)

    op.create_table('product_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('url', sqlmodel.AutoString(length=500), nullable=False),
    sa.Column('thumbnail_url', sqlmodel.AutoString(length=500), nullable=False),
    sa.Column('alt_text', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_images_product_id'), ['product_id'], unique=False)

    op.create_table('product_popularity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('purchase_count', sa.Integer(), nullable=False),
    sa.Column('cart_count', sa.Integer(), nullable=False),
    sa.Column('wishlist_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_popularity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_popularity_product_id'), ['product_id'], unique=True)

    op.create_table('product_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('body', sqlmodel.AutoString(length=2000), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='productreviewstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_reviews_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_reviews_user_id'), ['user_id'], unique=False)

    op.create_table('product_similarity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('similar_product_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('reason_code', sqlmodel.AutoString(length=80), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['similar_product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_similarity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_similarity_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_similarity_similar_product_id'), ['similar_product_id'], unique=False)

    op.create_table('product_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sku', sqlmodel.AutoString(length=120), nullable=False),
    sa.Column('name', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('mrp', sa.Float(), nullable=False),
    sa.Column('selling_price', sa.Float(), nullable=False),
    sa.Column('cost_price', sa.Float(), nullable=False),
    sa.Column('attributes_json', sqlmodel.AutoString(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('dimensions_json', sqlmodel.AutoString(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_variants_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_variants_sku'), ['sku'], unique=True)

    op.create_table('recommendation_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('placement', sa.Enum('HOME', 'PRODUCT_DETAIL', 'CART', 'POST_PURCHASE', 'SEARCH', name='recommendationplacement'), nullable=False),
    sa.Column('context_product_id', sa.Integer(), nullable=True),
    sa.Column('cache_key', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('product_ids_json', sqlmodel.AutoString(), nullable=False),
    sa.Column('reasons_json', sqlmodel.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['context_product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendation_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendation_cache_cache_key'), ['cache_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_recommendation_cache_context_product_id'), ['context_product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommendation_cache_user_id'), ['user_id'], unique=False)

    op.create_table('shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('vendor_order_id', sa.Integer(), nullable=True),
    sa.Column('awb', sqlmodel.AutoString(length=80), nullable=False),
    sa.Column('status', sa.Enum('PENDING_PAYMENT', 'CONFIRMED', 'PROCESSING', 'PACKED', 'SHIPPED', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED', 'RETURNED', name='orderstatus'), nullable=False),
    sa.Column('current_location', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('eta', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['vendor_order_id'], ['vendor_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipments_awb'), ['awb'], unique=True)
        batch_op.create_index(batch_op.f('ix_shipments_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipments_vendor_order_id'), ['vendor_order_id'], unique=False)

    op.create_table('user_product_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.Enum('VIEW', 'CLICK', 'SEARCH', 'ADD_TO_CART', 'ADD_TO_WISHLIST', 'PURCHASE', 'RATING', 'RECOMMENDATION_CLICK', name='recommendationeventtype'), nullable=False),
    sa.Column('placement', sa.Enum('HOME', 'PRODUCT_DETAIL', 'CART', 'POST_PURCHASE', 'SEARCH', name='recommendationplacement'), nullable=True),
    sa.Column('query_text', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('metadata_json', sqlmodel.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_product_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_product_events_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_product_events_user_id'), ['user_id'], unique=False)

    op.create_table('wishlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wishlist_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wishlist_items_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wishlist_items_user_id'), ['user_id'], unique=False)

    op.create_table('branch_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=True),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['logistics_branches.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('branch_inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_branch_inventory_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_branch_inventory_shipment_id'), ['shipment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_branch_inventory_variant_id'), ['variant_id'], unique=False)

    op.create_table('cart_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_at_add', sa.Float(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cart_items_cart_id'), ['cart_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cart_items_variant_id'), ['variant_id'], unique=False)

    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reserved_qty', sa.Integer(), nullable=False),
    sa.Column('reorder_level', sa.Integer(), nullable=False),
    sa.Column('reorder_qty', sa.Integer(), nullable=False),
    sa.Column('last_restocked_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_variant_id'), ['variant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_warehouse_id'), ['warehouse_id'], unique=False)

    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('vendor_order_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('variant_name', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('image_url', sqlmodel.AutoString(length=500), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'PACKED', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'RETURNED', name='vendororderstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.ForeignKeyConstraint(['vendor_order_id'], ['vendor_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_items_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_variant_id'), ['variant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_vendor_id'), ['vendor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_items_vendor_order_id'), ['vendor_order_id'], unique=False)

    op.create_table('pickup_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_order_id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ASSIGNED', 'PICKED_UP', 'RECEIVED_AT_HUB', 'FAILED', name='pickupjobstatus'), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('picked_up_at', sa.DateTime(), nullable=True),
    sa.Column('failure_reason', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['delivery_agents.id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['logistics_branches.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.ForeignKeyConstraint(['vendor_order_id'], ['vendor_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pickup_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pickup_jobs_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pickup_jobs_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pickup_jobs_shipment_id'), ['shipment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pickup_jobs_vendor_order_id'), ['vendor_order_id'], unique=False)

    op.create_table('shipment_proofs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('proof_type', sqlmodel.AutoString(length=30), nullable=False),
    sa.Column('otp_code', sqlmodel.AutoString(length=20), nullable=False),
    sa.Column('photo_url', sqlmodel.AutoString(length=500), nullable=False),
    sa.Column('signature_url', sqlmodel.AutoString(length=500), nullable=False),
    sa.Column('notes', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['delivery_agents.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shipment_proofs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipment_proofs_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipment_proofs_shipment_id'), ['shipment_id'], unique=False)

    op.create_table('shipment_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_PAYMENT', 'CONFIRMED', 'PROCESSING', 'PACKED', 'SHIPPED', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED', 'RETURNED', name='orderstatus'), nullable=False),
    sa.Column('location', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('remarks', sqlmodel.AutoString(length=500), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shipment_tracking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipment_tracking_shipment_id'), ['shipment_id'], unique=False)

    op.create_table('return_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('details', sqlmodel.AutoString(length=1000), nullable=False),
    sa.Column('refund_method', sqlmodel.AutoString(length=30), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'APPROVED', 'REJECTED', 'PICKED_UP', 'RECEIVED', 'REFUNDED', name='returnstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('return_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_return_requests_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_return_requests_order_item_id'), ['order_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_return_requests_user_id'), ['user_id'], unique=False)

    op.create_table('refund_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('return_request_id', sa.Integer(), nullable=False),
    sa.Column('payment_transaction_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='refundstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['payment_transaction_id'], ['payment_transactions.id'], ),
    sa.ForeignKeyConstraint(['return_request_id'], ['return_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refund_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refund_records_payment_transaction_id'), ['payment_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refund_records_return_request_id'), ['return_request_id'], unique=False)

    op.create_table('reverse_pickup_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('return_request_id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('REQUESTED', 'ASSIGNED', 'PICKED_UP', 'RETURNED_TO_VENDOR', 'CANCELLED', name='reversepickupstatus'), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('picked_up_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['delivery_agents.id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['logistics_branches.id'], ),
    sa.ForeignKeyConstraint(['return_request_id'], ['return_requests.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reverse_pickup_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reverse_pickup_jobs_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reverse_pickup_jobs_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reverse_pickup_jobs_return_request_id'), ['return_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reverse_pickup_jobs_shipment_id'), ['shipment_id'], unique=False)

    op.create_table('support_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('return_request_id', sa.Integer(), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('subject', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.AutoString(length=4000), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='supportticketstatus'), nullable=False),
    sa.Column('priority', sqlmodel.AutoString(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['return_request_id'], ['return_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_tickets_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_tickets_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_tickets_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_support_tickets_return_request_id'), ['return_request_id'], unique=False)

    op.create_table('chat_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_type', sa.Enum('ORDER', 'SUPPORT', 'GENERAL', name='chatconversationtype'), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('support_ticket_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['support_ticket_id'], ['support_tickets.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_conversations_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_conversations_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_conversations_support_ticket_id'), ['support_ticket_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_conversations_vendor_id'), ['vendor_id'], unique=False)

    op.create_table('chat_message_envelopes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender_user_id', sa.Integer(), nullable=False),
    sa.Column('sender_device_id', sa.Integer(), nullable=False),
    sa.Column('message_type', sqlmodel.AutoString(length=50), nullable=False),
    sa.Column('ciphertext', sqlmodel.AutoString(length=32768), nullable=False),
    sa.Column('header_json', sqlmodel.AutoString(), nullable=False),
    sa.Column('attachment_manifest_json', sqlmodel.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], ),
    sa.ForeignKeyConstraint(['sender_device_id'], ['chat_devices.id'], ),
    sa.ForeignKeyConstraint(['sender_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_message_envelopes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_message_envelopes_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_message_envelopes_sender_device_id'), ['sender_device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_message_envelopes_sender_user_id'), ['sender_user_id'], unique=False)

    op.create_table('chat_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('reported_by_user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('metadata_json', sqlmodel.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], ),
    sa.ForeignKeyConstraint(['reported_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_reports_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_reports_reported_by_user_id'), ['reported_by_user_id'], unique=False)

    op.create_table('chat_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('blob_url', sqlmodel.AutoString(length=1000), nullable=False),
    sa.Column('media_type', sqlmodel.AutoString(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('encrypted_file_key', sqlmodel.AutoString(length=4096), nullable=False),
    sa.Column('nonce', sqlmodel.AutoString(length=1024), nullable=False),
    sa.Column('sha256', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['chat_message_envelopes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_attachments_message_id'), ['message_id'], unique=False)

    op.create_table('chat_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('CUSTOMER', 'VENDOR', 'SUPPORT', name='chatparticipantrole'), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('last_read_message_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], ),
    sa.ForeignKeyConstraint(['last_read_message_id'], ['chat_message_envelopes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_participants_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_participants_user_id'), ['user_id'], unique=False)

    op.create_table('chat_read_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['chat_devices.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['chat_message_envelopes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_read_receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_read_receipts_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_read_receipts_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_read_receipts_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_read_receipts_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    pass
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipments_vendor_order_id'))
        batch_op.drop_index(batch_op.f('ix_shipments_order_id'))
        batch_op.drop_index(batch_op.f('ix_shipments_awb'))

    op.drop_table('shipments')
    with op.batch_alter_table('recommendation_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendation_cache_user_id'))
        batch_op.drop_index(batch_op.f('ix_recommendation_cache_context_product_id'))
        batch_op.drop_index(batch_op.f('ix_recommendation_cache_cache_key'))

    op.drop_table('recommendation_cache')
    with op.batch_alter_table('product_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_variants_sku'))
        batch_op.drop_index(batch_op.f('ix_product_variants_product_id'))

    op.drop_table('product_variants')
    with op.batch_alter_table('product_similarity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_similarity_similar_product_id'))
        batch_op.drop_index(batch_op.f('ix_product_similarity_product_id'))

    op.drop_table('product_similarity')
    with op.batch_alter_table('product_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_reviews_user_id'))
        batch_op.drop_index(batch_op.f('ix_product_reviews_product_id'))

    op.drop_table('product_reviews')
    with op.batch_alter_table('product_popularity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_popularity_product_id'))

    op.drop_table('product_popularity')
    with op.batch_alter_table('product_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_images_product_id'))

    op.drop_table('product_images')
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_warehouses_vendor_id'))

    op.drop_table('warehouses')
    with op.batch_alter_table('vendor_payouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_payouts_vendor_id'))

    op.drop_table('vendor_payouts')
    with op.batch_alter_table('vendor_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_orders_vendor_order_number'))
        batch_op.drop_index(batch_op.f('ix_vendor_orders_vendor_id'))
        batch_op.drop_index(batch_op.f('ix_vendor_orders_order_id'))

    op.drop_table('vendor_orders')
    with op.batch_alter_table('vendor_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_documents_vendor_id'))

    op.drop_table('vendor_documents')
    with op.batch_alter_table('vendor_bank_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_bank_accounts_vendor_id'))

    op.drop_table('vendor_bank_accounts')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_vendor_id'))
        batch_op.drop_index(batch_op.f('ix_products_slug'))
        batch_op.drop_index(batch_op.f('ix_products_category_id'))
        batch_op.drop_index(batch_op.f('ix_products_brand_id'))

    op.drop_table('products')
    with op.batch_alter_table('order_status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_status_history_order_id'))

    op.drop_table('order_status_history')
    with op.batch_alter_table('line_haul_trips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_line_haul_trips_manifest_id'))

    op.drop_table('line_haul_trips')
    with op.batch_alter_table('checkout_idempotency', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checkout_idempotency_user_id'))
        batch_op.drop_index(batch_op.f('ix_checkout_idempotency_order_id'))
        batch_op.drop_index(batch_op.f('ix_checkout_idempotency_idempotency_key'))

    op.drop_table('checkout_idempotency')
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendors_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_vendors_slug'))
        batch_op.drop_index(batch_op.f('ix_vendors_owner_user_id'))

    op.drop_table('vendors')
    with op.batch_alter_table('shipment_manifests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipment_manifests_origin_hub_id'))
        batch_op.drop_index(batch_op.f('ix_shipment_manifests_destination_hub_id'))
        batch_op.drop_index(batch_op.f('ix_shipment_manifests_code'))
        batch_op.drop_index(batch_op.f('ix_shipment_manifests_branch_id'))

    op.drop_table('shipment_manifests')
    op.drop_table('payment_webhooks')
    with op.batch_alter_table('payment_refunds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_refunds_transaction_id'))

    op.drop_table('payment_refunds')
    with op.batch_alter_table('payment_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_audit_logs_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_payment_audit_logs_event_type'))
        batch_op.drop_index(batch_op.f('ix_payment_audit_logs_actor_user_id'))

    op.drop_table('payment_audit_logs')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_user_id'))
        batch_op.drop_index(batch_op.f('ix_orders_payment_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_orders_order_number'))
        batch_op.drop_index(batch_op.f('ix_orders_address_id'))

    op.drop_table('orders')
    with op.batch_alter_table('delivery_agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delivery_agents_user_id'))
        batch_op.drop_index(batch_op.f('ix_delivery_agents_branch_id'))

    op.drop_table('delivery_agents')
    with op.batch_alter_table('chat_signed_prekeys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_signed_prekeys_key_id'))
        batch_op.drop_index(batch_op.f('ix_chat_signed_prekeys_device_id'))

    op.drop_table('chat_signed_prekeys')
    with op.batch_alter_table('chat_one_time_prekeys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_one_time_prekeys_key_id'))
        batch_op.drop_index(batch_op.f('ix_chat_one_time_prekeys_device_id'))

    op.drop_table('chat_one_time_prekeys')
    with op.batch_alter_table('wallet_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallet_ledger_user_id'))
        batch_op.drop_index(batch_op.f('ix_wallet_ledger_reference_id'))

    op.drop_table('wallet_ledger')
    with op.batch_alter_table('user_affinity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_affinity_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_affinity_category_id'))
        batch_op.drop_index(batch_op.f('ix_user_affinity_brand_id'))

    op.drop_table('user_affinity')
    with op.batch_alter_table('shipping_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipping_options_zone_id'))
        batch_op.drop_index(batch_op.f('ix_shipping_options_code'))

    op.drop_table('shipping_options')
    with op.batch_alter_table('payment_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_transactions_purchase_order_id'))
        batch_op.drop_index(batch_op.f('ix_payment_transactions_provider_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_payment_transactions_provider_pidx'))
        batch_op.drop_index(batch_op.f('ix_payment_transactions_idempotency_key'))

    op.drop_table('payment_transactions')
    with op.batch_alter_table('notificationpreference', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notificationpreference_user_id'))

    op.drop_table('notificationpreference')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_user_id'))

    op.drop_table('notification')
    with op.batch_alter_table('logistics_branches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_logistics_branches_zone_id'))
        batch_op.drop_index(batch_op.f('ix_logistics_branches_hub_id'))
        batch_op.drop_index(batch_op.f('ix_logistics_branches_code'))

    op.drop_table('logistics_branches')
    with op.batch_alter_table('gift_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gift_cards_redeemed_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_gift_cards_code'))

    op.drop_table('gift_cards')
    with op.batch_alter_table('chat_key_backups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_key_backups_user_id'))

    op.drop_table('chat_key_backups')
    with op.batch_alter_table('chat_devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_devices_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_devices_device_id'))

    op.drop_table('chat_devices')
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_carts_user_id'))

    op.drop_table('carts')
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_addresses_user_id'))

    op.drop_table('addresses')
    with op.batch_alter_table('logistics_hubs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_logistics_hubs_code'))

    op.drop_table('logistics_hubs')
    with op.batch_alter_table('delivery_zones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delivery_zones_code'))

    op.drop_table('delivery_zones')
    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coupons_code'))

    op.drop_table('coupons')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_slug'))
        batch_op.drop_index(batch_op.f('ix_categories_parent_id'))

    op.drop_table('categories')
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brands_slug'))

    op.drop_table('brands')
    # ### end Alembic commands ###
