# Generated by Django 5.0.14 on 2026-02-09 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_coupon_order_coupon_code_order_coupon_discount_and_more"),
        ("users", "0003_user_avatar_url_user_email_verified_user_phone_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="idempotency_key",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["user", "idempotency_key"], name="idx_orders_user_idempotency"),
        ),
    ]
