import type { CatalogCategory, CatalogProduct } from '@/types';

export const mockCategories: CatalogCategory[] = [
  { id: 'cat-home', parent_id: null, name: 'Home Atelier', slug: 'home-atelier', level: 1, description: 'Refined living accents.', attributes: [] },
  { id: 'cat-tech', parent_id: null, name: 'Smart Gear', slug: 'smart-gear', level: 1, description: 'Modern electronics and accessories.', attributes: [] },
  { id: 'cat-style', parent_id: null, name: 'Personal Style', slug: 'personal-style', level: 1, description: 'Wardrobe details and daily essentials.', attributes: [] },
  { id: 'cat-gifts', parent_id: null, name: 'Gift Studio', slug: 'gift-studio', level: 1, description: 'Curated bundles for moments that matter.', attributes: [] },
];

export const mockProducts: CatalogProduct[] = [
  {
    id: 'prod-1',
    vendor_id: 'vendor-1',
    category: { id: 'cat-home', name: 'Home Atelier', slug: 'home-atelier' },
    brand: { id: 'brand-1', name: 'Northline', slug: 'northline' },
    name: 'Sculpted Table Lamp',
    slug: 'sculpted-table-lamp',
    short_description: 'Warm ceramic glow for focused corners.',
    description: 'A tactile lamp built for worktops, sideboards, and reading nooks.',
    specifications: {},
    status: 'active',
    avg_rating: 4.8,
    review_count: 132,
    view_count: 904,
    is_featured: true,
    images: [],
    variants: [],
    min_selling_price: 94,
    in_stock: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod-2',
    vendor_id: 'vendor-2',
    category: { id: 'cat-tech', name: 'Smart Gear', slug: 'smart-gear' },
    brand: { id: 'brand-2', name: 'Signal Foundry', slug: 'signal-foundry' },
    name: 'Noise-Cut Earbuds',
    slug: 'noise-cut-earbuds',
    short_description: 'Clean sound with commuter-grade isolation.',
    description: 'Pocket-sized listening gear with adaptive modes and long battery life.',
    specifications: {},
    status: 'active',
    avg_rating: 4.7,
    review_count: 84,
    view_count: 540,
    is_featured: true,
    images: [],
    variants: [],
    min_selling_price: 149,
    in_stock: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod-3',
    vendor_id: 'vendor-3',
    category: { id: 'cat-style', name: 'Personal Style', slug: 'personal-style' },
    brand: { id: 'brand-3', name: 'Twill & Tide', slug: 'twill-tide' },
    name: 'Structured Carry Tote',
    slug: 'structured-carry-tote',
    short_description: 'Everyday utility with polished geometry.',
    description: 'Soft-sided structure, hidden pockets, and commuter-ready capacity.',
    specifications: {},
    status: 'active',
    avg_rating: 4.9,
    review_count: 56,
    view_count: 301,
    is_featured: false,
    images: [],
    variants: [],
    min_selling_price: 128,
    in_stock: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod-4',
    vendor_id: 'vendor-4',
    category: { id: 'cat-gifts', name: 'Gift Studio', slug: 'gift-studio' },
    brand: { id: 'brand-4', name: 'Parcel Ritual', slug: 'parcel-ritual' },
    name: 'Celebration Gift Box',
    slug: 'celebration-gift-box',
    short_description: 'Ready-to-ship pairing for fast gifting.',
    description: 'A mixed artisan bundle prepared for birthdays, launches, and thank-yous.',
    specifications: {},
    status: 'active',
    avg_rating: 4.6,
    review_count: 41,
    view_count: 227,
    is_featured: true,
    images: [],
    variants: [],
    min_selling_price: 72,
    in_stock: false,
    created_at: new Date().toISOString(),
  },
];
